services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: bank_account_payment_php
        volumes:
            - .:/app
        working_dir: /app
        stdin_open: true
        tty: true
